import path from 'path';
import config from '../config/index.js';

/**
 * Service processing uploaded files and preparing standardized file metadata objects
 * 
 * @param {Array<Express.Multer.File>} files - Array of uploaded files from Multer
 * @returns {{ files: Array<object>, count: number }}
 */
export const processUploads = (files) => {
  const processedFiles = files.map((file) => {
    // Use the unique UUID basename generated by Multer as the file ID
    const fileId = path.parse(file.filename).name;
    const extension = path.extname(file.originalname).toLowerCase();
    
    // Normalize relative path using forward slashes for cross-platform API consistency
    const relativePath = `${config.uploadDir}/${file.filename}`.replace(/\\/g, '/');

    return {
      id: fileId,
      originalName: file.originalname,
      storedName: file.filename,
      mimeType: file.mimetype,
      extension,
      size: file.size,
      path: relativePath
    };
  });

  return {
    files: processedFiles,
    count: processedFiles.length
  };
};

export default {
  processUploads
};
