/**
 * SatVistaar Advanced Geospatial Vision AI Supported Task Intents
 */
export const INTENTS = {
  VQA: 'VQA',
  CAPTIONING: 'CAPTIONING',
  FEATURE_IDENTIFICATION: 'FEATURE_IDENTIFICATION',
  CHANGE_ANALYSIS: 'CHANGE_ANALYSIS',
  OPTICAL_SAR_FUSION: 'OPTICAL_SAR_FUSION',
  // Advanced Geospatial Intelligence Suite Intents
  TIME_SERIES: 'TIME_SERIES',
  FLOOD_ANALYSIS: 'FLOOD_ANALYSIS',
  CHANGE_MATRIX: 'CHANGE_MATRIX',
  OPTICAL_SAR_DIFFERENCE: 'OPTICAL_SAR_DIFFERENCE',
  OBJECT_INVENTORY: 'OBJECT_INVENTORY',
  // Disaster Response Intelligence Mode Intents
  DISASTER_RESPONSE: 'DISASTER_RESPONSE',
  NISAR_ANALYSIS: 'NISAR_ANALYSIS',
  UNKNOWN: 'UNKNOWN'
};

/**
 * List of valid supported tasks for user requestedTask validation
 */
export const VALID_REQUESTED_TASKS = [
  INTENTS.VQA,
  INTENTS.CAPTIONING,
  INTENTS.FEATURE_IDENTIFICATION,
  INTENTS.CHANGE_ANALYSIS,
  INTENTS.OPTICAL_SAR_FUSION,
  INTENTS.TIME_SERIES,
  INTENTS.FLOOD_ANALYSIS,
  INTENTS.CHANGE_MATRIX,
  INTENTS.OPTICAL_SAR_DIFFERENCE,
  INTENTS.OBJECT_INVENTORY,
  INTENTS.DISASTER_RESPONSE,
  INTENTS.NISAR_ANALYSIS
];

export default INTENTS;
