import BaseTool from './base.tool.js';
import { INTENTS } from '../agent/intents.js';
import { getProvider } from '../providers/index.js';

import normalizeVLMResponse from '../services/responseNormalizer.js';
import { extractGroundingFromText, validateGroundingRegions } from '../utils/groundingValidator.js';

export class FeatureIdentificationTool extends BaseTool {
  constructor() {
    super({
      name: 'feature-identification-tool',
      task: INTENTS.FEATURE_IDENTIFICATION,
      description: 'Feature and object identification tool for approximate visual grounding in satellite imagery',
      version: '1.0.0'
    });
  }

  async execute(context) {
    const { query, imagePaths = [], modelSelection = {} } = context;
    const { selectedModel, isMock } = modelSelection;

    // Synthetic Mock Response handling
    if (isMock || !selectedModel || selectedModel.provider === 'mock') {
      const mockRegions = validateGroundingRegions([
        { label: 'Building Cluster', x: 0.22, y: 0.28, width: 0.24, height: 0.20, confidence: 0.88 },
        { label: 'Road Network', x: 0.50, y: 0.35, width: 0.15, height: 0.45, confidence: 0.82 },
        { label: 'Vegetation Zone', x: 0.65, y: 0.15, width: 0.28, height: 0.22, confidence: 0.79 }
      ]);

      return this.createResult({
        answerText: `[Mock Feature Identification] Identified primary visual features in scene for query "${query}":\n- Buildings & Structures: Densely populated cluster in upper-left quadrant.\n- Road Network: Transport artery running vertically.\n- Vegetation Cover: Agricultural crop fields occupying upper-right sectors.`,
        confidence: null,
        grounding: {
          type: 'approximate',
          isMock: true,
          regions: mockRegions
        },
        evidence: [
          {
            type: 'approximate_location',
            source: 'vlm-grounding',
            description: 'Approximate visual region identification (non-pixel-level segmentation)'
          }
        ],
        modelName: 'mock-vlm',
        modelVersion: '1.0.0',
        provider: 'mock',
        parametersUsed: { mode: 'mock' },
        warnings: [
          'MVP Visual Feature Identification notice: Approximate visual grounding generated by generic VLM. Pixel-exact geospatial segmentation is not claimed.'
        ],
        status: 'success'
      });
    }

    const promptText = `You are performing approximate visual grounding on a satellite or aerial image.
Identify the feature requested by the user: "${query}".
Return a concise natural-language answer AND approximate image regions for the identified feature.
For each region provide normalized coordinates between 0 and 1:
- x: left to right (0 = left, 1 = right)
- y: top to bottom (0 = top, 1 = bottom)
- width: 0 to 1
- height: 0 to 1

Optionally return a JSON block formatted as:
\`\`\`json
{
  "answer": "Natural language summary of visible features...",
  "regions": [
    { "label": "${query}", "x": 0.2, "y": 0.3, "width": 0.25, "height": 0.2, "confidence": 0.85 }
  ]
}
\`\`\`
Only return regions that are visually supported by the image.
Do not claim pixel-perfect segmentation or exact geospatial coordinates.
If the feature cannot be confidently located, return an empty regions array.
Do not output <think> or internal reasoning blocks.`;

    try {
      const providerInstance = getProvider(selectedModel.provider);
      if (!providerInstance) {
        throw new Error(`Provider instance '${selectedModel.provider}' not registered.`);
      }
      let vlmResponse = await providerInstance.analyze({
        prompt: promptText,
        imagePaths,
        task: this.task,
        modelName: selectedModel.model
      });

      const extracted = extractGroundingFromText(vlmResponse.answerText);

      // Support explicit provider grounding boxes (e.g. Python ML Engine)
      const rawBoxes = vlmResponse.groundingBoxes || vlmResponse.boundingBoxes || vlmResponse.bounding_boxes || vlmResponse.regions || vlmResponse.evidence;
      if (rawBoxes && Array.isArray(rawBoxes) && rawBoxes.length > 0) {
        const mapped = rawBoxes.map(b => {
          if (b.box && Array.isArray(b.box) && b.box.length >= 4) {
            const [ymin, xmin, ymax, xmax] = b.box;
            return {
              label: b.label || query,
              x: xmin,
              y: ymin,
              width: Math.max(0.02, xmax - xmin),
              height: Math.max(0.02, ymax - ymin),
              confidence: b.confidence || 0.88
            };
          } else if (b.x !== undefined && b.y !== undefined && b.width !== undefined && b.height !== undefined) {
            return {
              label: b.label || query,
              x: b.x,
              y: b.y,
              width: Math.max(0.02, b.width),
              height: Math.max(0.02, b.height),
              confidence: b.confidence || 0.88
            };
          } else if (b.ymin !== undefined && b.xmin !== undefined) {
            return {
              label: b.label || query,
              x: b.xmin,
              y: b.ymin,
              width: Math.max(0.02, (b.xmax || b.xmin + 0.2) - b.xmin),
              height: Math.max(0.02, (b.ymax || b.ymin + 0.2) - b.ymin),
              confidence: b.confidence || 0.88
            };
          }
          return null;
        }).filter(Boolean);

        if (mapped.length > 0) {
          extracted.regions = validateGroundingRegions(mapped);
        }
      }

      const textToNormalize = extracted.cleanText || vlmResponse.answerText;
      let normalized = normalizeVLMResponse(textToNormalize, this.task);
      const combinedWarnings = [
        'MVP Visual Feature Identification notice: Approximate visual grounding generated by generic VLM. Pixel-exact geospatial segmentation is not claimed.',
        ...(vlmResponse.warnings || []),
        ...(normalized.warnings || [])
      ];

      // Single Retry rule if answer is empty or generic
      if (normalized.isLowQuality) {
        combinedWarnings.push('Initial Feature Identification provider response was generic; a single quality retry was requested.');
        try {
          const retryResponse = await providerInstance.analyze({
            prompt: `${promptText}\nIMPORTANT: State explicitly where the requested feature is located in the image or state clearly that it is not visible.`,
            imagePaths,
            task: this.task,
            modelName: selectedModel.model
          });
          const retryExtracted = extractGroundingFromText(retryResponse.answerText);
          const retryNormalized = normalizeVLMResponse(retryExtracted.cleanText || retryResponse.answerText, this.task);
          if (!retryNormalized.isLowQuality && retryNormalized.answerText) {
            normalized = retryNormalized;
            if (retryExtracted.regions.length > 0) {
              extracted.regions = retryExtracted.regions;
            }
          }
        } catch (retryErr) {
          combinedWarnings.push(`Feature Identification quality retry failed: ${retryErr.message}`);
        }
      }

      return this.createResult({
        answerText: normalized.answerText,
        confidence: vlmResponse.confidence,
        grounding: {
          type: 'approximate',
          isMock: false,
          regions: extracted.regions
        },
        evidence: [
          {
            type: 'approximate_location',
            source: selectedModel.provider,
            description: `VLM approximate visual grounding (${extracted.regions.length} region(s) identified)`
          }
        ],
        modelName: selectedModel.name || selectedModel.model,
        modelVersion: selectedModel.model,
        provider: selectedModel.provider,
        parametersUsed: vlmResponse.parametersUsed,
        warnings: combinedWarnings,
        status: normalized.isLowQuality ? 'partial' : 'success'
      });
    } catch (err) {
      return this.createResult({
        answerText: null,
        confidence: null,
        evidence: [],
        modelName: selectedModel.name || 'vlm',
        provider: selectedModel.provider || 'unknown',
        warnings: [`Feature Identification VLM execution failed: ${err.message}`],
        status: 'failed'
      });
    }
  }
}

export const featureIdentificationTool = new FeatureIdentificationTool();
export default featureIdentificationTool;
